Correct linking of warcsum with autotools
I don't know much about autotools, but blindly guessing that we need to refer
to symbols that actually exist to link against libraries works out. Explicit
-l options in CFLAGS come too early (before object files) so linking against DSOs
fails with a message like:

    /usr/bin/ld: warcsum-warcsum.o: undefined reference to symbol 'inflateReset2@@ZLIB_1.2.3.4'